on:
  push:
    branches: [main]

name: Build and deploy GH Pages

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
