on:
  push:
    branches: [main]

name: Build and deploy GH Pages

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 20.11

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build front
        run: |
          yarn prod

      - name: Zola build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
